name: CI
on:
  push:
    branches:
      - master
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: 'x64'
      - name: Install requirements
        run:  pip install -r requirements.txt
  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: login to docker
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: build image
        run: docker build -t $NAME .
      - name: build image
        run: docker build -t $NAME $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile
      - name: push image to docker hub
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
